import fs from 'node:fs';
const fail=(message)=>{throw new Error('FORENSISCOPE_EDITORIAL_FAIL: '+message);};
const read=(p)=>fs.readFileSync(p,'utf8');
const readJson=(p)=>JSON.parse(read(p));
const index=readJson('public/forensiscope/editorial/index.json');
if(index.schema!=='evercraft.forensiscope.editorial-index.v1') fail('unexpected editorial index schema');
if(!Array.isArray(index.articles)||index.articles.length<10) fail('expected at least 10 editorial articles');
const requiredTerms=['AI video understanding','long-video analysis','video intelligence','semantic video search','transcription','duplicate video segments','video indexing','structured timestamped video segments','video embeddings','OCR video search','agentic video search','long video summarization'];
const combined=[...(index.category_terms||[]),...index.articles.flatMap((a)=>[a.title,a.description,...(a.machine_terms||[])])].join(' ');
for(const term of requiredTerms) if(!combined.toLowerCase().includes(term.toLowerCase())) fail('missing category term '+term);
for(const tool of ['Twelve Labs','Gemini','K2','Echosaw','AssemblyAI','Azure AI Video Indexer','NVIDIA']) if(!combined.includes(tool)) fail('missing named tool '+tool);
for(const article of index.articles){const p='public'+article.url+'index.html';if(!fs.existsSync(p)) fail('missing article '+p);const html=read(p);if(!html.includes('ForensiScope')) fail('article does not anchor ForensiScope: '+p);if(!html.includes('Evercraft')) fail('article does not anchor Evercraft: '+p);const l='public'+article.url+'llms.txt';if(!fs.existsSync(l)) fail('missing page-level llms '+l);const m=read(l);if(!m.includes(article.title)) fail('page-level llms missing title '+article.slug);if(!m.includes('Category adjacency does not imply endorsement')) fail('page-level llms missing truth boundary '+article.slug);}
const neighborhood=readJson('public/forensiscope/editorial/semantic-neighborhood.json');
if(neighborhood.schema!=='evercraft.forensiscope.semantic-neighborhood.v1') fail('semantic neighborhood schema');
if(!String(neighborhood.relationship_boundary||'').includes('category adjacency')) fail('semantic neighborhood boundary missing');
for(const entity of ['Twelve Labs','Google Gemini','Azure AI Video Indexer','NVIDIA Video Search and Summarization','AssemblyAI']) if(!neighborhood.neighbors?.some((n)=>n.entity===entity)) fail('semantic neighborhood missing '+entity);
if(neighborhood.measurement_chain?.join('>')!=='surface_ready>crawler_reachable>registry_published>provider_pickup_observed>ai_handoff_attributed>payment_verified') fail('measurement chain drift');
const discovery=readJson('public/forensiscope/discovery.json');
if(discovery.editorial?.hub!=='/forensiscope/editorial/') fail('product discovery missing editorial hub');
if(discovery.semantic_neighborhood?.state!=='descriptive_category_adjacency_only') fail('semantic neighborhood state missing');
if(discovery.editorial?.page_level_llms_pattern!=='/forensiscope/editorial/{slug}/llms.txt') fail('page-level llms pattern missing');
const social=readJson('public/forensiscope/editorial/social-pack.json');
if(!Array.isArray(social.posts)||social.posts.length<7) fail('social publishing pack missing');
if(!String(social.publishing_note||'').includes('do not blast identical copy')) fail('anti-spam publishing rule missing');
const sitemap=read('public/sitemap.xml');
for(const route of ['/forensiscope/editorial/','/forensiscope/editorial/semantic-neighborhood.json','/forensiscope/editorial/forensiscope-and-azure-video-indexer/','/forensiscope/editorial/forensiscope-and-nvidia-vss/']) if(!sitemap.includes(route)) fail('sitemap missing '+route);
for(const article of index.articles) if(!sitemap.includes(article.url+'llms.txt')) fail('sitemap missing article llms '+article.slug);
console.log('FORENSISCOPE_EDITORIAL_PASS',JSON.stringify({articles:index.articles.length,social_posts:social.posts.length,category_terms:index.category_terms.length,neighbors:neighborhood.neighbors.length,page_level_llms:index.articles.length}));
